In [11]:
# Q1. How do we load the dataset and see the first 5 rows?

In [6]:
import pandas as pd

In [7]:
print(pd.__version__)

2.2.2

In [8]:
df=pd.read_csv('/movies.csv')

In [9]:
type(df)

pandas.core.frame.DataFrame

In [10]:
df

,id,name,year,rating,certificate,duration,genre,votes,gross_income,directors_id,directors_name,stars_id,stars_name,description
0,tt0068646,The Godfather,1972,9.2,R,175 min,"Crime, Drama",1798749,"134,966,411",nm0000338,Francis Ford Coppola,"nm0000008,nm0000199,nm0001001,nm0000473","Marlon Brando,Al Pacino,James Caan,Diane Keaton",The aging patriarch of an organized crime dyna...
1,tt5113044,Minions: The Rise of Gru,2022,7.3,PG,87 min,"Animation, Adventure, Comedy","1,220","134,966,411","nm0049633,nm1556070,nm3646390","Kyle Balda,Brad Ableson,Jonathan del Val","nm0136797,nm1853544,nm0000273,nm0378245","Steve Carell,Pierre Coffin,Alan Arkin,Taraji P...",The untold story of one twelve-year-old's drea...
2,tt7657566,Death on the Nile,2022,6.3,PG-13,127 min,"Crime, Drama, Mystery","121,063","134,966,411",nm0000110,Kenneth Branagh,"nm5290643,nm0000906,nm0000110,nm1258970","Tom Bateman,Annette Bening,Kenneth Branagh,Rus...","While on vacation on the Nile, Hercule Poirot ..."
3,tt8115900,The Bad Guys,2022,6.9,PG,100 min,"Animation, Adventure, Comedy","23,090","134,966,411",nm2010048,Pierre Perifel,"nm0005377,nm0549505,nm5377144,nm0732497","Sam Rockwell,Marc Maron,Awkwafina,Craig Robinson",Several reformed yet misunderstood criminal an...
4,tt10809742,Collision,2022,3.8,TV-MA,99 min,"Crime, Drama, Thriller",656,"134,966,411",nm1926494,Fabien Martorell,"nm1339181,nm0456810,nm12651040,nm7357127","Tessa Jubber,Langley Kirkwood,Zoey Sneedon,Bon...",Freedom always comes at a price.
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19803,tt0459423,Kahaani Gudiya Ki...: True Story of a Woman,2008,6.2,Not Rated,112 min,"Biography, Drama",41,"44,435",nm1909606,Prabhakar Shukla,"nm0244890,nm0952232,nm1056425,nm6389513","Divya Dutta,Arif Zakaria,Rajpal Naurang Yadav,...","A tragic saga about a woman named Gudiya, whos..."
19804,tt0119621,Mark Twain's America in,1998,6.5,G,52 min,"Documentary, Biography",48,"2,281,741",nm0522844,Stephen Low,"nm0000843,nm0640297,nm4700843,nm1838044","Anne Bancroft,Dennis O'Connor,Kim Parr,LeeAnn ...",Interweaves Twain's life and times with the li...
19805,tt0168950,Let It Come Down: The Life of Paul Bowles,1998,6.9,Not Rated,75 min,"Documentary, Biography",125,"9,188",nm0047028,Jennifer Baichwal,"nm0101247,nm0123221,nm0155822,nm0159383","Paul Bowles,William S. Burroughs,Cherifa,Moham...",Add a Plot
19806,tt0267563,Hybrid,2000,7.4,Not Rated,92 min,"Documentary, Biography",146,"159,403","/name/nm0566144/,/name/nm1084921/","Monteith McCollum,Milford Beeghly",nm1084921,Milford Beeghly,The life story of Milford Beeghly: Iowa farmer...
19807,tt0116481,Hands on a Hardbody: The Documentary,1997,7.6,PG,98 min,"Documentary, Comedy, Drama",2167,"492,876",nm0082835,S.R. Bindler,"nm0021057,nm1828145,nm0185044,nm0190040","Sid Allen,Brent Baskin,Greg Cox,J.C. Crum",Twenty-four contestants compete in an enduranc...

In [12]:
df.head() # First 5 rows by default when no value in ()

,id,name,year,rating,certificate,duration,genre,votes,gross_income,directors_id,directors_name,stars_id,stars_name,description
0,tt0068646,The Godfather,1972,9.2,R,175 min,"Crime, Drama",1798749,"134,966,411",nm0000338,Francis Ford Coppola,"nm0000008,nm0000199,nm0001001,nm0000473","Marlon Brando,Al Pacino,James Caan,Diane Keaton",The aging patriarch of an organized crime dyna...
1,tt5113044,Minions: The Rise of Gru,2022,7.3,PG,87 min,"Animation, Adventure, Comedy","1,220","134,966,411","nm0049633,nm1556070,nm3646390","Kyle Balda,Brad Ableson,Jonathan del Val","nm0136797,nm1853544,nm0000273,nm0378245","Steve Carell,Pierre Coffin,Alan Arkin,Taraji P...",The untold story of one twelve-year-old's drea...
2,tt7657566,Death on the Nile,2022,6.3,PG-13,127 min,"Crime, Drama, Mystery","121,063","134,966,411",nm0000110,Kenneth Branagh,"nm5290643,nm0000906,nm0000110,nm1258970","Tom Bateman,Annette Bening,Kenneth Branagh,Rus...","While on vacation on the Nile, Hercule Poirot ..."
3,tt8115900,The Bad Guys,2022,6.9,PG,100 min,"Animation, Adventure, Comedy","23,090","134,966,411",nm2010048,Pierre Perifel,"nm0005377,nm0549505,nm5377144,nm0732497","Sam Rockwell,Marc Maron,Awkwafina,Craig Robinson",Several reformed yet misunderstood criminal an...
4,tt10809742,Collision,2022,3.8,TV-MA,99 min,"Crime, Drama, Thriller",656,"134,966,411",nm1926494,Fabien Martorell,"nm1339181,nm0456810,nm12651040,nm7357127","Tessa Jubber,Langley Kirkwood,Zoey Sneedon,Bon...",Freedom always comes at a price.

In [15]:
df.sample(5) # will give you random 5 values

,id,name,year,rating,certificate,duration,genre,votes,gross_income,directors_id,directors_name,stars_id,stars_name,description
16205,tt1588895,Uncle Boonmee Who Can Recall His Past Lives,2010,6.7,Not Rated,114 min,"Drama, Fantasy",15730,"183,605",nm0917405,Apichatpong Weerasethakul,"nm3914142,nm1178649,nm1616807,nm3913567","Thanapat Saisaymar,Jenjira Pongpas,Sakda Kaewb...","Dying of kidney disease, a man spends his last..."
13967,tt0092933,Dudes,1987,5.6,R,90 min,"Adventure, Comedy","1,483","13,684,949",nm0790715,Penelope Spheeris,"nm0001083,nm0736263,nm0281359,nm0898962","Jon Cryer,Daniel Roebuck,Flea,Lee Ving",3 punk loving dudes in NYC need a change and d...
8438,tt0363163,帝國毀滅,2004,8.2,R-12,156 min,"Biography, Drama, History",351476,"5,509,040",nm0386570,Oliver Hirschbiegel,"nm0004486,nm0487884,nm0559890,nm0477810","Bruno Ganz,Alexandra Maria Lara,Ulrich Matthes...","Traudl Junge, the final secretary for Adolf Hi..."
4250,tt0902952,Acolytes,2008,5.5,Not Rated,91 min,"Crime, Drama, Horror","2,345","138,634",nm0382054,Jon Hewitt,"nm0249291,nm1168915,nm2600074,nm2267063","Joel Edgerton,Michael Dorman,Sebastian Gregory...",Three teenagers blackmail a serial killer.
8471,tt4648786,哈莉特：廢奴之戰,2019,6.6,PG-13,125 min,"Action, Biography, Drama","26,318","74,700,000",nm0501435,Kasi Lemmons,"nm7248827,nm1847117,nm1502434,nm7153679","Cynthia Erivo,Janelle Monáe,Leslie Odom Jr.,Jo...",The extraordinary tale of Harriet Tubman's esc...

In [13]:
# Q2. What are the data types of each column?

In [17]:
df.head() # first step data reading

,id,name,year,rating,certificate,duration,genre,votes,gross_income,directors_id,directors_name,stars_id,stars_name,description
0,tt0068646,The Godfather,1972,9.2,R,175 min,"Crime, Drama",1798749,"134,966,411",nm0000338,Francis Ford Coppola,"nm0000008,nm0000199,nm0001001,nm0000473","Marlon Brando,Al Pacino,James Caan,Diane Keaton",The aging patriarch of an organized crime dyna...
1,tt5113044,Minions: The Rise of Gru,2022,7.3,PG,87 min,"Animation, Adventure, Comedy","1,220","134,966,411","nm0049633,nm1556070,nm3646390","Kyle Balda,Brad Ableson,Jonathan del Val","nm0136797,nm1853544,nm0000273,nm0378245","Steve Carell,Pierre Coffin,Alan Arkin,Taraji P...",The untold story of one twelve-year-old's drea...
2,tt7657566,Death on the Nile,2022,6.3,PG-13,127 min,"Crime, Drama, Mystery","121,063","134,966,411",nm0000110,Kenneth Branagh,"nm5290643,nm0000906,nm0000110,nm1258970","Tom Bateman,Annette Bening,Kenneth Branagh,Rus...","While on vacation on the Nile, Hercule Poirot ..."
3,tt8115900,The Bad Guys,2022,6.9,PG,100 min,"Animation, Adventure, Comedy","23,090","134,966,411",nm2010048,Pierre Perifel,"nm0005377,nm0549505,nm5377144,nm0732497","Sam Rockwell,Marc Maron,Awkwafina,Craig Robinson",Several reformed yet misunderstood criminal an...
4,tt10809742,Collision,2022,3.8,TV-MA,99 min,"Crime, Drama, Thriller",656,"134,966,411",nm1926494,Fabien Martorell,"nm1339181,nm0456810,nm12651040,nm7357127","Tessa Jubber,Langley Kirkwood,Zoey Sneedon,Bon...",Freedom always comes at a price.

RESEARCH ON THE MOVIE CERTIFICATES
Data about Data : MetaData

In [18]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19808 entries, 0 to 19807
Data columns (total 14 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   id              19808 non-null  object
 1   name            19808 non-null  object
 2   year            19808 non-null  int64
 3   rating          19808 non-null  float64
 4   certificate     19808 non-null  object
 5   duration        19808 non-null  object
 6   genre           19808 non-null  object
 7   votes           19808 non-null  object
 8   gross_income    19808 non-null  object
 9   directors_id    19808 non-null  object
 10  directors_name  19808 non-null  object
 11  stars_id        19808 non-null  object
 12  stars_name      19808 non-null  object
 13  description     19808 non-null  object
dtypes: float64(1), int64(1), object(12)
memory usage: 2.1+ MB

In [19]:
# Q3. How do we clean the `duration` column? (e.g., `'175 min'` → `175`)

In [20]:
df["duration"]

0        175 min
1         87 min
2        127 min
3        100 min
4         99 min
          ...
19803    112 min
19804     52 min
19805     75 min
19806     92 min
19807     98 min
Name: duration, Length: 19808, dtype: object

In [21]:
df["duration"].str.replace('min', '')

0        175
1         87
2        127
3        100
4         99
         ...
19803    112
19804     52
19805     75
19806     92
19807     98
Name: duration, Length: 19808, dtype: object

In [26]:
df["duration"]=df["duration"].str.replace('min', '')
df["duration"]=df["duration"].str.replace(',', '') # since e.g : 5,690 have comma so we have to remove to make it int

In [27]:
df["duration"].astype(int)

0        175
1         87
2        127
3        100
4         99
        ...
19803    112
19804     52
19805     75
19806     92
19807     98
Name: duration, Length: 19808, dtype: int64

In [ ]:
# Q4. How do we clean the `gross` column and `votes` column?

In [29]:
df["votes"]

0        1798749
1          1,220
2        121,063
3         23,090
4            656
          ...
19803         41
19804         48
19805        125
19806        146
19807       2167
Name: votes, Length: 19808, dtype: object

In [31]:
df["votes"]=df["votes"].str.replace(',',"")

In [32]:
df["votes"]=df["votes"].astype(int)

In [33]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19808 entries, 0 to 19807
Data columns (total 14 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   id              19808 non-null  object
 1   name            19808 non-null  object
 2   year            19808 non-null  int64
 3   rating          19808 non-null  float64
 4   certificate     19808 non-null  object
 5   duration        19808 non-null  object
 6   genre           19808 non-null  object
 7   votes           19808 non-null  int64
 8   gross_income    19808 non-null  object
 9   directors_id    19808 non-null  object
 10  directors_name  19808 non-null  object
 11  stars_id        19808 non-null  object
 12  stars_name      19808 non-null  object
 13  description     19808 non-null  object
dtypes: float64(1), int64(2), object(11)
memory usage: 2.1+ MB

In [34]:
#gross_income

In [35]:
df["gross_income"]

0        134,966,411
1        134,966,411
2        134,966,411
3        134,966,411
4        134,966,411
            ...
19803         44,435
19804      2,281,741
19805          9,188
19806        159,403
19807        492,876
Name: gross_income, Length: 19808, dtype: object

In [41]:
df["gross_income"]=df["gross_income"].str.replace(',',"")
df["gross_income"]=df["gross_income"].str.replace('$',"")
df["gross_income"]=df["gross_income"].str.replace('M',"")

In [45]:
df["gross_income"]=df["gross_income"].astype(float)

In [46]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19808 entries, 0 to 19807
Data columns (total 14 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   id              19808 non-null  object
 1   name            19808 non-null  object
 2   year            19808 non-null  int64
 3   rating          19808 non-null  float64
 4   certificate     19808 non-null  object
 5   duration        19808 non-null  object
 6   genre           19808 non-null  object
 7   votes           19808 non-null  int64
 8   gross_income    19808 non-null  float64
 9   directors_id    19808 non-null  object
 10  directors_name  19808 non-null  object
 11  stars_id        19808 non-null  object
 12  stars_name      19808 non-null  object
 13  description     19808 non-null  object
dtypes: float64(2), int64(2), object(10)
memory usage: 2.1+ MB

In [47]:
# Q5. How many missing values are in each column?

In [48]:
df.isnull()

,id,name,year,rating,certificate,duration,genre,votes,gross_income,directors_id,directors_name,stars_id,stars_name,description
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19803,False,False,False,False,False,False,False,False,False,False,False,False,False,False
19804,False,False,False,False,False,False,False,False,False,False,False,False,False,False
19805,False,False,False,False,False,False,False,False,False,False,False,False,False,False
19806,False,False,False,False,False,False,False,False,False,False,False,False,False,False
19807,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [49]:
df.isnull().sum()

id                0
name              0
year              0
rating            0
certificate       0
duration          0
genre             0
votes             0
gross_income      0
directors_id      0
directors_name    0
stars_id          0
stars_name        0
description       0
dtype: int64

In [50]:
df.isna() # Same as isnull()

,id,name,year,rating,certificate,duration,genre,votes,gross_income,directors_id,directors_name,stars_id,stars_name,description
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19803,False,False,False,False,False,False,False,False,False,False,False,False,False,False
19804,False,False,False,False,False,False,False,False,False,False,False,False,False,False
19805,False,False,False,False,False,False,False,False,False,False,False,False,False,False
19806,False,False,False,False,False,False,False,False,False,False,False,False,False,False
19807,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [52]:
# Q9. What are the unique certificates in the dataset?

In [53]:
df["certificate"]

0                R
1               PG
2            PG-13
3               PG
4            TV-MA
           ...
19803    Not Rated
19804            G
19805    Not Rated
19806    Not Rated
19807           PG
Name: certificate, Length: 19808, dtype: object

In [54]:
df["certificate"].unique()

array(['R', 'PG', 'PG-13', 'TV-MA', 'Not Rated', 'Approved', 'TV-14',
       'NC-17', 'Unrated', 'G', 'Passed', 'GP', 'X', 'M/PG', 'M', 'TV-PG',
       'TV-G', '12', 'TV-13', 'TV-Y7-FV', 'MA-17', 'AO', '18', 'R-15',
       'R-12', 'R-18', 'PG-12', '6+', 'TV-Y7', 'TV-Y', 'MA-13'],
      dtype=object)

In [56]:
df["certificate"].nunique() # give no. of unique value

31

In [57]:
# Q10. How many movies were released each year?

In [58]:
df.count()

id                19808
name              19808
year              19808
rating            19808
certificate       19808
duration          19808
genre             19808
votes             19808
gross_income      19808
directors_id      19808
directors_name    19808
stars_id          19808
stars_name        19808
description       19808
dtype: int64

In [59]:
df["year"].count() # total no. of movies  For all years

np.int64(19808)

In [63]:
df.groupby("year")["id"].count() # For each year number of movies released in that year

year
1894      1
1898      1
1902      2
1903      1
1913      3
       ...
2018    736
2019    657
2020    467
2021    470
2022    174
Name: id, Length: 114, dtype: int64

In [64]:
# other way

In [66]:
df["year"].value_counts()  # Here I have listed year than counted how many time they occured which also means movie released in that year

year
2018    736
2017    714
2016    665
2019    657
2014    640
       ...
1919      1
1898      1
1894      1
1917      1
1903      1
Name: count, Length: 114, dtype: int64